### ISSUE TITLE
S3 support

### ISSUE THREAD

**Issue by artemverbo** [spatie/laravel-glide#31]
Hello again! You've mentioned in a readme, that were planning at some point to add other disk drivers support, would +1 an S3 please. We have common "file uploads" going to/serving from s3, but images that require Glide cropping and so on are still on local disk, ideally would like to move all the uploads to Amazon. Not sure though about the best practices regarding cache for example. Have seen a few stackoverflow questions/discussions on having originals on s3, cache on local or disabling cache completely and just serving from s3...

**Comment by freekmurze** [comment]
All take a look at it soon. If you need S3 uploads now, you could take a look at our [medialibrary-package](https://github.com/spatie/laravel-medialibrary)

**Comment by artemverbo** [comment]
Thanks heaps, looking at medialibrary!

**Comment by paulfry** [comment]
+1 for S3. Would be a fantastic addition to this package.

**Comment by freekmurze** [comment]
Due to time constraints, S3 support isn't coming any time soon. If you really need this, feel free to submit a PR.

**Comment by tillkruss** [comment]
+1 for S3 read/write support.

**Comment by freekmurze** [comment]
@tillkruss Take a look at [our medialibrary package](https://docs.spatie.be/laravel-medialibrary/v4/introduction) which can copy Glide manipulated images to S3.
