### ISSUE TITLE
class 'League\Glide\Api\Manipulator\Orientation' not found

### ISSUE THREAD

**Issue by baopham** [spatie/laravel-glide#32]
Looks like it's due to this commit: thephpleague/glide@544d51f381b656b5ed31a4c55c0544adab4daa2b

**Comment by freekmurze** [comment]
I'm unable to replicate this issue. I tried rotating an image and it work. Could you run composer update to make sure you have all the latest version. If it still fails, reopen this issue and please provide me the code to replicate the problem.

**Comment by AlexanderPoellmann** [comment]
@baopham seems like you set minimum-stability to dev which is why composer pulls a work in progress version of league/glide which contains some major refactors - including renaming some namespaces `League\Glide\Api\Manipulator\Orientation` will be `League\Glide\Manipulators\Orientation` etc.
