### ISSUE TITLE
Does this package support full urls?

### ISSUE THREAD

**Issue by tobz-nz** [spatie/laravel-glide#36]
My project is pulling images from a third party, so will not be on any 'local' filesystems.

**Comment by freekmurze** [comment]
The images that you want to convert must be available locally. So you should copy the images from the third party to your local disk first.

**Comment by tobz-nz** [comment]
ok, thanks.

... feature request?

**Comment by freekmurze** [comment]
I don't see copying the image from an url as a responsability of this package. 

You can add this to your application with a couple of lines of code:
```php
$url = 'https://thirdparty.com/image.jpg';
file_put_contents($pathOnYourDisk, file_get_contents($url));
```

Make sure you trust that third party and verify that you have copied an image by using a function like [finfo_file](http://www.php.net/manual/en/function.finfo-file.php).
