### ISSUE TITLE
Class 'League\Glide\Http\UrlBuilderFactory' not found

### ISSUE THREAD

**Issue by Hobstweedl** [spatie/laravel-glide#38]
Tried installing this in Laravel 5 and tried using the example usage for displaying an image on the fly. Error is returned.

**Comment by freekmurze** [comment]
The class exists in the 0.3.* version of Glide: https://github.com/thephpleague/glide/blob/0.3.5/src/Http/UrlBuilderFactory.php

Which version of Glide are you pulling in?

**Comment by Hobstweedl** [comment]
Composer was pulling in the dev branch. Have no idea why it was, but switching to 0.3.5 fixed the issue
