### ISSUE TITLE
Target [League\Flysystem\FilesystemInterface] is not instantiable

### ISSUE THREAD

**Issue by ahmadbadpey** [spatie/laravel-glide#39]
I follow all install instructions that you saied. and I write a custom Route to show images : 

`Route::get('/showImage/{w}/{h}/{src}', function (League\Glide\Server $server,  Illuminate\Http\Request $request) {
		$server->outputImage($request);
	})->where('src', '.+');`

but when run the Route bellow error is shown : 
`BindingResolutionException in Container.php line 745:
Target [League\Flysystem\FilesystemInterface] is not instantiable.`

**Comment by freekmurze** [comment]
Did you install the service provider?
