### ISSUE TITLE
Appending GlideImage::load as Attribute to Model

### ISSUE THREAD

**Issue by Jaspur** [spatie/laravel-glide#40]
I wanna append an attribute to my Photo Model with a full URL including signature and the dimensions.

Normally I'm doing it in the view, and it works:
```
<img src="{{ GlideImage::load($photo->path, ['w' => 100, 'h' => 100, 'fit' => 'crop']) }}">
```

But I want it in my JSON-response for Angular-reasons. So I did this in my Model:
```
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

use GlideImage;

class Photo extends Model
{
    protected $fillable = ['foobar', 'path'];
    protected $appends = ['thumb'];

    public function getThumbAttribute()
    {
        return GlideImage::load($this->path, ['w' => 241, 'h' => 187, 'fit' => 'crop']);
    }
}

```
But that returns just an empty:
<img width="515" alt="schermafdruk 2015-11-18 15 56 37" src="https://cloud.githubusercontent.com/assets/4254854/11244283/0dce572c-8e0d-11e5-8191-4b31838724d5.png">
What I expected was an URL like: ```/img/photos/f02cd882f546a30cb435b22c1e337f7b.jpg?w=100&amp;h=100&amp;fit=crop&amp;s=f9b52d8c713ac525da0d6accff50822e```

**Comment by freekmurze** [comment]
Try this:
```php
  return GlideImage::load($this->path, ['w' => 241, 'h' => 187, 'fit' => 'crop'])->getURL();
```

**Comment by Jaspur** [comment]
That quick ;-) Thnx!
