### ISSUE TITLE
Glide composer dependency broken

### ISSUE THREAD

**Issue by harrygr** [spatie/laravel-glide#41]
The version for the `thephpleague/glide` dependency is listed as `0.3.*`.

The `0.3-dev` tag fulfils this requirement but the directory structure of the phpleague library has been changed in this version resulting in this error:

>Class 'League\Glide\Api\Manipulator\Orientation' not found in /home/vagrant/Sites/creuset/vendor/spatie/laravel-glide/src/Spatie/Glide/GlideApiFactory.php on line 29

**Comment by harrygr** [comment]
It seems the problem only occurs when `minimum-stability` is set to `dev` in composer.json which was the case in my project. Still good to be aware of upcoming change.

**Comment by freekmurze** [comment]
Ok, thanks for letting me know. I think the next version of Glide will be a major one. I'll make sure this package will get compatible with that version.
