### ISSUE TITLE
this package can only manipulate image locally

### ISSUE THREAD

**Issue by argb** [spatie/laravel-glide#42]

**Comment by freekmurze** [comment]
Could you please describe to problem in more detail. If possible also provide sample code with which the problem can be recreated.

**Comment by argb** [comment]
@freekmurze I just mean the package hard coded Local filesystem :
protected function setImageSource()
    {
        return (new Filesystem(new Local(
            $this->glideConfig['source']['path']
        )));
    }

**Comment by freekmurze** [comment]
There's [a note in the readme regarding this](https://github.com/spatie/laravel-glide#other-filesystems). Feel free to submit a PR if you need extra functionality.

**Comment by argb** [comment]
@freekmurze thanks :)
