### ISSUE TITLE
the output image by this way can't be cached by browser,how to solve?

### ISSUE THREAD

**Issue by argb** [spatie/laravel-glide#43]
Images was out put by php,can't be cached.If I put images in /public directory,output by nginx,it can be cached.
How to fix the problem?

**Comment by freekmurze** [comment]
I'm afraid that I don't understand the problem you are having. Could you please give more info on this problem? If possible post some code with which the issue can be recreated.

**Comment by argb** [comment]
@freekmurze Solved,because I used another package,laravel-httpcache(https://github.com/barryvdh/laravel-httpcache),this package don't work well,and it would change the request headers,generate a new response with every request,not cached.
