### ISSUE TITLE
route code

### ISSUE THREAD

**Issue by amin101** [spatie/laravel-glide#44]
hi , how should i implement code in routes.php to process image?
this is my code but it doesnt work

```
$server = League\Glide\ServerFactory::create([
    'source' => 'images/offer',
    'cache' => 'images/cache',
]);
Route::match(['get','post'],'img/{other?}', function(\Illuminate\Http\Request $request){
   /$server->outputImage($request);
  
});
```

**Comment by freekmurze** [comment]
When glancing your code example I see that ` /$server` is a syntax error.

Your question does not concern this package, but Glide itself. If you have further issue concerning this code, you should post your issue there.
