### ISSUE TITLE
Php 7 required

### ISSUE THREAD

**Issue by afraca** [spatie/laravel-glide#46]
Packagists show ~14k installs for this package. I'm with a small web-app firm (4 people), and we simply have too much old sites running to port everything to php 7. We'll get there in about 1 year I guess, we have 120 sites running (low traffic). 

Our new system is built upon Laravel 5.1, and we like to keep up with new development now. However, getting our vps to php 7 is simply not an option in the nearby future. 

We really like this package, and would like to continue using it. I've read tons on the cool new stuff in 7, but for a big package breaking with many people seems like a bad plan! 

There is the option of maintaining two branches at the same time. With the Python 2/3 problems, lots of big libraries have tried really hard to be compatible with 2.X and 3.X , none of the big ones did complete dropping of 2.X

**Comment by freekmurze** [comment]
You can still use the [version 2 branch of this package](https://github.com/spatie/laravel-glide/tree/v2) which has Laravel 5.1 / PHP 5.x. compatiblity. We still use that version for our own older projects as well.

**Comment by forxer** [comment]
Why did you choose PHP 7.0? Is there a real need in the code of the package? What feature of PHP 7 do you use?

**Comment by freekmurze** [comment]
[Here is some background on that decision](https://murze.be/2016/01/why-we-are-requiring-php-7-for-our-new-packages/)

**Comment by forxer** [comment]
Thank you for this detailed answer. That makes sense and I understand that.

Nevertheless, we can not always migrate for reasons as diverse and relevant as yours, although we have the needs satisfied by the new packages. But we will find other solutions while continuing to use your awesome packages :)

Also thank you for your work.
