### ISSUE TITLE
3.0 depends on php 7. Really needed?

### ISSUE THREAD

**Issue by renege** [spatie/laravel-glide#47]
Hello, it's a very strict requirement that it needs php 7. My host doesnt support it. The original package of league/glide doesn't need php7 for league/glide 1.0.0. And i wanna use the 1.0.0 leage's glide because of the new features they added.

**Comment by freekmurze** [comment]
I've blogged about [why we are requiring php 7 for the new major versions of all our packages](https://murze.be/2016/01/why-we-are-requiring-php-7-for-our-new-packages/).
