### ISSUE TITLE
Call to undefined method GlideImage::create()

### ISSUE THREAD

**Issue by notflip** [spatie/laravel-glide#49]
Immediatly after install I get the following error when testing in my routes.

    FatalErrorException in Facade.php line 218:
    Call to undefined method Spatie\Glide\GlideImage::create()

I followed the installation instructions, any idea what I might be doing wrong?

**Comment by freekmurze** [comment]
The `create`-method cannot be used in conjunction with the facade. Could you try to replace the `create`-method by `setSourceFile`? Please let me know if that works for you.

I'll update the docs to make this more clear.

**Comment by notflip** [comment]
It's also giving an error (sorry for the late reply)

FatalErrorException in Facade.php line 218:
Call to undefined method Spatie\Glide\GlideImage::setSourceFile()

This is the code i'm using to test
    Route::get('/img/{path}', function($path) {
        GlideImage::setSourceFile($path)->outputImage($path, ['w' => 300, 'h' => 400]);
    });

**Comment by freekmurze** [comment]
Are you using the latest version of this package (v3)?

**Comment by notflip** [comment]
"spatie/laravel-glide": "^2.2". I'll take a look at the latest version. Thank you

**Comment by prashantidealittechno** [comment]
Hello @notflip  Please include the line at the top of the route.php 
```php
use Spatie\Glide\GlideImage;
```
