### ISSUE TITLE
Glide Image Api on Laravel-medialibrary

### ISSUE THREAD

**Issue by PhilMarc** [spatie/laravel-glide#51]
Using Medialibrary, I can successfully modify the media conversions, using `setManipulations` in my Model file, for instance orientating thumbnail pic of 90 degrees:

`//Post.php`
`    public function registerMediaConversions(){`
`    $this->addMediaConversion('thumb')->setManipulations(['or' => 90])->performOnCollections('images');`
`        }`

However, I would like to perform this manipulation on the original media itself, not on the conversion.
In order to do that, I tried to modify my upload controller this way:

`//UploadController.php`
`$post->addMedia($image)->manipulations(['or' => '90'])->toMediaLibrary('images');`

But the manipulation doesn't work. Any clue of what I am doing wrong? Is the Glide Api supported only for media conversions?

**Comment by sebastiandedeyne** [comment]
Moved to the medialibrary repository: https://github.com/spatie/laravel-medialibrary/issues/193
