### ISSUE TITLE
setManipulations Watermark path

### ISSUE THREAD

**Issue by PhilMarc** [spatie/laravel-glide#52]
I am trying to add a watermark to my image:

```
$this->addMediaConversion('large')
    ->setManipulations(['fm' => 'jpg', 'mark' => 'watermark.png', 'markw' => '40', 'markh' => '40', 'markpad' => '15', 'markpos' => 'top-left'])
    ->performOnCollections('images');
```

Following the Glide doc (http://glide.thephpleague.com/1.0/api/watermarks/) I added a new filesystem for watermarks, in the laravel's `config/filesystems.php` file.

However, my generated thumb doesnt have any watermark on it. And there is no log error report.

Where should I place my `watermark.png` file ? I tried in `storage/images` and `storage/watermarks` and even modifying  `'mark' => storage_path('images/watermark.png')` but I can't get it working.

**Comment by freekmurze** [comment]
Could try using the absolute path to you watermark file?

**Comment by tlandn** [comment]
Hi, I tried absolute path

GlideImage::create(public_path().'/uploads/posts/cropped-1555.jpg')
    ->modify(['mark' => '/home/vagrant/Code/mysite/public/uploads/posts/mark-100h.png'])
    ->save(public_path(). '/output.jpg');

with no luck.

**Comment by freekmurze** [comment]
This has been fixed in v.3.0.1. You can now use the absolute path in the `mark` parameter.

**Comment by PhilMarc** [comment]
Tested it on local and production, works like a charm using `public_path()`
Thanks for the fix!
