### ISSUE TITLE
2.3.1 bugged

### ISSUE THREAD

**Issue by Jaspur** [spatie/laravel-glide#57]
Since the latest update from v2 I get this errors:
```
Internention\Image\Exception\NotSupportedException · GET /img/photos/_270_2101912-Foobarjpg_5735a2cb3519a
Driver () could not be instantiated.
```

**Comment by freekmurze** [comment]
I'll take a look at this now.

**Comment by freekmurze** [comment]
Could you try the current version from master?

**Comment by fgreinus** [comment]
Same for me. Am on newest version of laravel-medialibrary, that makes use of laravel-glide. 

I use laravel-glide version 2.3.1 and medialibrary version 3.17.4

**Comment by freekmurze** [comment]
Busy working on a fix. Gimme a couple of minutes

**Comment by fgreinus** [comment]
Thank you really much :). :heart_eyes:

**Comment by freekmurze** [comment]
Version 2.3.2 of the package contains a fix.

Run `composer update` to install it.

Let me know if that works for you.

**Comment by fgreinus** [comment]
Sadly still not working. Same error as before. Happens only when i try to upload an image. Files that arent eligible for thumbnail creation make no problems.

**Comment by freekmurze** [comment]
Are you sure you're running 2.3.2 of this package?

**Comment by fgreinus** [comment]
Updating dependencies (including require-dev)
  - Removing spatie/laravel-glide (2.3.1)
  - Installing spatie/laravel-glide (2.3.2)
    Downloading: 100%

**Comment by freekmurze** [comment]
Investigating...

**Comment by fgreinus** [comment]
Thanks :)

**Comment by freekmurze** [comment]
Can't seem to reproduce this in the latest version.

Could you see if you see this line in your code base?

https://github.com/spatie/laravel-glide/blob/master/src/GlideServiceProvider.php#L24

**Comment by fgreinus** [comment]
The directory structure seems to be a bit different.

In my version it's         $this->mergeConfigFrom(__DIR__.'/../../config/laravel-glide.php', 'laravel-glide');

So one directory higher than in your version. composer.lock file says 2.3.2 is installed.

**Comment by freekmurze** [comment]
Strange... I've tested it on a fresh project here, and it all seems to work. 

Could you try nuking your `vendor` directory and running `composer install`?

**Comment by fgreinus** [comment]
Did that.. still the same problem.

**Comment by freekmurze** [comment]
The link I set earlier was wrong (that was master), you should see this code in your install: 

https://github.com/spatie/laravel-glide/blob/2.3.2/src/Spatie/Glide/GlideServiceProvider.php

**Comment by fgreinus** [comment]
Yeah.. thats the code i have locally. Also the config file you are merging there into the laravel config is existent and has 'driver' => 'gd' in it...
I have no idea.

**Comment by freekmurze** [comment]
Are you still seeing the error "Driver () could not be instantiated." ? Could you try to set a dd statement right after the `mergeConfig` line to see what the contents of the `config(laravel-glide)` is?

**Comment by fgreinus** [comment]
Seems like the register function in the GlideServiceProvider is not even called when using medialibrary. Any dd Statement does not have any effect.

**Comment by freekmurze** [comment]
I've made a change. Could you try requiring dev-master and see if that version works?

**Comment by fgreinus** [comment]
Yeah that works :).

**Comment by fgreinus** [comment]
Would you mind releasing that fix in a new version via packagist? Thanks btw for your fast response :).

**Comment by freekmurze** [comment]
version 2.3.3 contains the fix. Reopen this issue if, after upgrading, you're still having troubles.
