### ISSUE TITLE
How can I make a circle Image?

### ISSUE THREAD

**Issue by prashantidealittechno** [spatie/laravel-glide#61]
I know I can make a circle Image with watermark, is their any other way to do Circle Image?

**Comment by freekmurze** [comment]
What do you mean with "circle" image? Could you give an example of what you're doing now and what you're hoping to achieve?

**Comment by prashantidealittechno** [comment]
**Thanks you** for your precious time, 
Yes Please check the link below,
http://cloudinary.com/documentation/image_transformations

**Is their any option for round off the corners in laravel glide?**

**Comment by freekmurze** [comment]
Seems like this currently [is not possible](http://glide.thephpleague.com/1.0/api/quick-reference/). You'd best open up an issue on [the Glide repo](https://github.com/thephpleague/glide) to request the feature
