### ISSUE TITLE
ErrorException in GlideImage.php line 30

### ISSUE THREAD

**Issue by TnCoders** [spatie/laravel-glide#64]
After my issue #62 i updated to verion 3.1.0

I have this in my Config
 `
return [

    /*
     * The driver that will be used to create images. Can be set to gd or imagick.
     */
    'driver' => 'gd',

    /*
     * Glide will search for images in this directory
     *
     */
    'source' => [
        'path' => storage_path('images'),
    ],

    /*
     * The directory Glide will use to store it's cache
     * A .gitignore file will be automatically placed in this directory
     * so you don't accidentally end up committing these images
     *
     */
    'cache' => [
        'path' => storage_path('glide/cache'),
    ],

    /*
     * URLs to generated images will start with this string
     *
     */
    'baseURL' => 'img',

    /*
     * The maximum allowed total image size in pixels
     */
    'maxSize' => 2000 * 2000,

    /*
     * Glide has a feature to sign each generated URL with
     * a key to avoid the visitors of your site to alter the URL
     * manually
     */
    'useSecureURLs' => true,
];
`

I have image Called foot.jpg in Storage/App/Images

` <img src="{{ GlideImage::create('foot.jpg')->modify(['w'=> 200, 'filt'=>'greyscale']) }}" />`

but i have this error:

![erreur_exception](https://cloud.githubusercontent.com/assets/24681177/22291125/033e60ec-e305-11e6-9533-2e4866715c9b.PNG)

**Comment by sebastiandedeyne** [comment]
Are you still experiencing this error?

Gonna close this issue for now since it's been inactive for a while. Feel free to reopen if necessary!

**Comment by youngbuckscrew** [comment]
Im experiencing the same issue.
