### ISSUE TITLE
max size not show

### ISSUE THREAD

**Issue by alinasiri1367** [spatie/laravel-glide#65]
Hello
This package also was shown the photos to enlarge?
like this :
![2]
(https://cloud.githubusercontent.com/assets/10260838/25134427/c502b386-2464-11e7-87da-003ecd28ac70.jpg)
` 'maxSize' => 12000 * 12000,`

**Comment by freekmurze** [comment]
Do my knowledge `maxSize` is not a valid parameter.

Please refer to the Glide documentation to learn which parameters are possible: http://glide.thephpleague.com/

**Comment by alinasiri1367** [comment]
I not fount any parameters.
