### ISSUE TITLE
file_exists(): open_basedir restriction in effect. 

### ISSUE THREAD

**Issue by jorenvh1** [spatie/laravel-glide#66]
Hey

I'm using glide to do some image manipulations on an uploaded image.
When testing locally, everything works but when we deploy to a combell shared hosting, I get the following error:
`file_exists(): open_basedir restriction in effect. File(/data/sites/web/scribblrmtantwerpeu/tmp/phpmkV0Wn/f1b906abc87cd37f44c511f8dd7acc88) is not within the allowed path(s): (/data/sites/web/scribblrmtantwerpeu:/usr/local/php-7.1/lib/php:/usr/bin:/tmp:/data/vendor-scripts:/data/sites/web/disabled:/etc/ssl/certs)`

I guess this is trying to check if the file exists in the tmp folder. The problem is that it starts from the basepath, which we don't have access to. The root of our shared hosting in this case is 'scribblrmtantwerpeu' 

Any way we can fix this?

**Comment by freekmurze** [comment]
This problem is probably caused by the underlying package [Glide](https://github.com/thephpleague/glide). Open an issue at their repo.

(pro-tip: don't use shared hosting 😬)
