### ISSUE TITLE
Animated gifs

### ISSUE THREAD

**Issue by websuasive** [spatie/laravel-glide#92]
We would like to be able to handle animated gifs in our application but the animations are being striped when images are compressed using glide.

According to the Imagick documentation, it can handle animated gifs and so can v3 of Intervention Image. 

However in laravel-glide library, composer.json shows

```
        "intervention/image": "^2.7",
```

So are there any plans to update the library to use the latest version so that animated gifs can be supported?

Or is there any other way of achieving animated gifs as I can't see anything in the documentation or searching online.

Thank you for your help!

**Comment by freekmurze** [comment]
I'd accept a PR that adds compatibility with intervention/image v3. If all tests pass, I'll likely merge it in quickly.
